<!-- $Header: /u02/cvsroot/hockeystats/menu.jsp,v 1.1 2002/09/15 01:53:23 tom Exp $ -->

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<HTML>

<HEAD>
<TITLE>Main Menu</TITLE>
</HEAD>

<BODY BGCOLOR="FFFFFF">

<H5>
Jon's Adult Hockey<BR>League<BR>
<BR><HR COLOR="3300FF" NOSHADE WIDTH=120 ALIGN=LEFT><BR>
Pictures<BR>
<BR><HR COLOR="3300FF" NOSHADE WIDTH=120 ALIGN=LEFT><BR>
Schedule<BR>
<BR><HR COLOR="3300FF" NOSHADE WIDTH=120 ALIGN=LEFT><BR>
Goals & Assists<BR>
<BR><HR COLOR="3300FF" NOSHADE WIDTH=120 ALIGN=LEFT><BR>
Penalties & Goalie<BR>Stats, Points<BR>
<BR><HR COLOR="3300FF" NOSHADE WIDTH=120 ALIGN=LEFT><BR>
League Rules<BR>
<BR><HR COLOR="3300FF" NOSHADE WIDTH=120 ALIGN=LEFT><BR>
Links<BR>
<BR><HR COLOR="3300FF" NOSHADE WIDTH=120 ALIGN=LEFT><BR>
</H5><BR>

</BODY)
</HTML>
