# local makefile, where the sources are.

# where the root dir is
TOP_DIR         =..
#where the classes are put under the class dir (required for "make clean")
PACKAGE_DIR     =hockeystats

include $(TOP_DIR)/Makefile.include
