# $Header: /u02/cvsroot/hockeystats/WEB-INF/hockeystats/util/db/Makefile,v 1.1 2002/09/15 01:53:23 tom Exp $
# local makefile, where the sources are.

# where the root dir is
TOP_DIR         =../../..
#where the classes are put under the class dir (required for "make clean")
PACKAGE_DIR     =hockeystats/util/db

include $(TOP_DIR)/Makefile.include
